name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Notify Build Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          text: Build failed
          description: The build failed on ${{ github.sha }} by ${{ github.actor }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Trigger deployment
        if: github.event_name == 'push'
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Notify deployment
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: ${{ github.event_name == 'push' && success() }}
        with:
          severity: info
          text: A new version has been deployed
          description: to ${{ vars.PROD_URL }} by ${{ github.actor }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    runs-on: ubuntu-20.04
    needs: simple_deployment_pipeline
    if: ${{github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
